In [1]:
import numpy as np
rng = np.random.default_rng()


In [2]:
matrix_list = np.array(8)

for i in range(8):
    # Generates a pair (stack of 2) of 4x4 matrices
    matrix_list = rng.random((2, 3*(i+1), 3*(i+1)))
    
print(matrix_list)

    


[[[0.66762089 0.15840873 0.05071242 ... 0.64877811 0.17970209 0.63486827]
  [0.31839011 0.94170273 0.17352495 ... 0.68642569 0.45342316 0.33494442]
  [0.43846762 0.5106925  0.65193884 ... 0.9358739  0.08480484 0.55878153]
  ...
  [0.76912015 0.25291239 0.81761458 ... 0.22536435 0.70979526 0.81210678]
  [0.73945176 0.98625116 0.11516442 ... 0.49940566 0.33936941 0.71637284]
  [0.56732063 0.94506405 0.60132637 ... 0.72872515 0.91223654 0.87232116]]

 [[0.37704877 0.51124988 0.15280931 ... 0.94435497 0.8468582  0.46912206]
  [0.87565848 0.23149003 0.76262956 ... 0.20169682 0.40972775 0.73056549]
  [0.28027434 0.83306427 0.63541074 ... 0.25353172 0.77523459 0.48680572]
  ...
  [0.81175374 0.96464076 0.64272567 ... 0.64667888 0.27332356 0.60533866]
  [0.21953956 0.48868605 0.6230939  ... 0.04760924 0.07818685 0.09609724]
  [0.71442963 0.08399912 0.88903593 ... 0.76522949 0.21982602 0.95546   ]]]
