In [7]:
#challenge 8
import numpy as np

def is_Diag_Dom(A):
    m,n  = A.shape #retrieve dimensions
    
    
    
    for i in range(m):
        diag = abs(A[i,i])
        sum = 0
        for j in range(n): #add up non-diag elements
            if j != i:
                sum += abs(A[i,j])
            #print(diag, sum) this was a sanity check
        if diag < sum: #checks condition for dominance
            return False
        
    return True
                

In [8]:
A1 = np.array([[5, 1, 1],
               [2, 7, 1],
               [1, 1, 6]])

A2 = np.array([[10, -1, 2, 0],
               [-1, 11, -1, 3],
               [2, -1, 10, -1],
               [0, 3, -1, 8]])

A3 = np.array([[4, 0, 0],
               [1, 1, 5],
               [2, -1, 6]])


In [9]:
print("Array 1: \n", A1)
print("Is it diagonally dominant?", is_Diag_Dom(A1))
print("\nArray 2:\n", A2)
print("Is it diagonally dominant?", is_Diag_Dom(A2))
print("\nArray 3: \n", A3)
print("Is it diagonally dominant?", is_Diag_Dom(A3))

Array 1: 
 [[5 1 1]
 [2 7 1]
 [1 1 6]]
Is it diagonally dominant? True

Array 2:
 [[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]]
Is it diagonally dominant? True

Array 3: 
 [[ 4  0  0]
 [ 1  1  5]
 [ 2 -1  6]]
Is it diagonally dominant? False
